title: Palharez Blog
email: xeduardopalhares@gmail.com
description:
author: Eduardo Palhares
baseurl: "/blog"
url: "https://palharez.github.io/"

# Social Profiles
twitter_username: xeduardopjr
github_username: palharez
facebook_username:
linkedin_username: eduardopalhares

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-146854912-1 # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
